version: "3"

networks:
  schoco:
    external: true

services:
  schoco-backend:
    image: phitux/schoco-backend:latest-dev
    container_name: schoco-backend
    restart: always
    user: "1000:1000"
    group_add:
      - ${DOCKER_GROUP_ID}
    environment:
      - FULL_DATA_PATH=/path/to/my/data
      - MAX_CONTAINERS=4
      - SECRET_KEY=secret
      - TEACHER_KEY=teacherkey
      - GITEA_USERNAME=schoco
      - GITEA_PASSWORD=schoco1234
      - GITEA_HOST=http://schoco-gitea:3000
    networks:
      - schoco
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

  schoco-nginx:
    image: phitux/schoco-nginx:latest-dev
    container_name: schoco-nginx
    restart: always
    group_add:
      - ${DOCKER_GROUP_ID}
    networks:
      - schoco
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:8080"

  schoco-gitea:
    image: gitea/gitea:1.17.3
    container_name: schoco-gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__security__INSTALL_LOCK=true
    networks:
      - schoco
    volumes:
      - ./gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
