version: "3"

networks:
  schoco:
    name: schoco

services:
  schoco-backend:
    image: phitux/schoco-backend:<tag> # use the newest tag, see https://hub.docker.com/r/phitux/schoco-backend/tags
    container_name: schoco-backend
    restart: always
    user: "1000:1000" # find out your user-id (uid) and group-id (gid) with 'id' in your bash
    group_add:
      - ${DOCKER_GROUP_ID} # run in your bash: export DOCKER_GROUP_ID=$(getent group docker | cut -d: -f3)
    environment:
      - FULL_DATA_PATH=/path/to/my/data 
      # same as (left part of) first volume - but here as FULL PATH!!!

      - MAX_CONTAINERS=4 
      # sets the amount of java-workers

      - SECRET_KEY=secret 
      # used for session token

      - TEACHER_KEY=teacherkey 
      # this is the 'password' that is used to create new teacher-accounts. It must only be known to the teachers.

      - COOKIES_TAG=1.0.0 (not yet implemented) 
      # can be left away right now

      - GITEA_USERNAME=schoco 
      # this is the username of the gitea-user (see last image in this yaml-file) 

      - GITEA_PASSWORD=schoco1234 
      # and that is the password of the gitea-user. 
      # Actually both username and password can stay like this, if you use the gitea-image from this yaml-file and if gitea is not made public (default)!

      - GITEA_HOST=http://schoco-gitea:3000
      # stays like this, if you use the gitea-image from this yaml-file and if gitea is not made public (default)!
      # change it to your domain, if you use a public gitea-instance
    networks:
      - schoco
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

  schoco-nginx:
    image: phitux/schoco-nginx:<tag> # use the newest tag, see https://hub.docker.com/r/phitux/schoco-nginx/tags
    container_name: schoco-nginx
    restart: always
    group_add:
      - ${DOCKER_GROUP_ID} # run in your bash: export DOCKER_GROUP_ID=$(getent group docker | cut -d: -f3)
    networks:
      - schoco
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:8080" # adapt the left host-port to your needs

  schoco-gitea:
    image: gitea/gitea:1.17.3 # you could probably use a newer version, but API-changes might break something...
    container_name: schoco-gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__security__INSTALL_LOCK=true
    networks:
      - schoco
    volumes:
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
