"""added must_change_password to user

Revision ID: 075dad69ab65
Revises: f42eca714ce0
Create Date: 2024-01-03 15:24:45.889915

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
from sqlalchemy.sql import false
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075dad69ab65'
down_revision: Union[str, None] = 'f42eca714ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('must_change_password', sa.Boolean(), nullable=True, server_default=false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'must_change_password')
    # ### end Alembic commands ###
