"""added enable_tests to homework

Revision ID: f42eca714ce0
Revises: f031d57aa4e6
Create Date: 2023-10-21 16:20:39.538990

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42eca714ce0'
down_revision: Union[str, None] = 'f031d57aa4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('enable_tests', sa.Boolean(), nullable=True, default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'enable_tests')
    # ### end Alembic commands ###
